# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd openplant-extensibility-sample
    npm install -g vsts-npm-auth --registry https://registry.npmjs.com --always-auth false 
    vsts-npm-auth -config .npmrc 
    npm run installAll
    npm run build
  displayName: 'npm install and build'
