# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: npmAuthenticate@0
  inputs:
    workingFile: 'openplant-extensibility-sample/.npmrc'

- script: |
    cd openplant-extensibility-sample
    npm run installAll
    npm run build
  displayName: 'npm install and build'
